### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by pauloxnet** [tartley/colorama#399]
Can you publish a new release with official support for Python 3.11/3.12 ?

**Comment by MichaelCurrie** [comment]
This now the last package in my build that complains about a Python 3.11 environment.  I'm sure if you ran the tests it would probably work fine. :D  Thank you!

In fact, I see the latest version of the code (at https://github.com/tartley/colorama/blob/master/pyproject.toml) is already changed to support any python >= 3.9, but the last version released to PyPI is from 3 years ago,  https://github.com/tartley/colorama/releases/tag/0.4.6, on 2022-10-02, which had the following lines:

```toml
[project]
name = "colorama"
requires-python = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*, !=3.6.*"
```

So someone with PyPI admin rights just needs to 

1. bump the colorama package version and 

2. build and upload it:

```
python -m build
twine check dist/*
twine upload dist/*
```
